### ISSUE TITLE
npm install fails with "Error: Cannot find module 'pinkie-promise'"

### ISSUE THREAD

**Issue by nissimhania** [misterGF/CoPilot#47]
$sudo npm install
Password:
Error: Cannot find module 'pinkie-promise'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/lib/index.js:3:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'pinkie-promise'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by misterGF** [comment]
Closing this was not able to replicate . Please pull the latest and give it another go. Please reopen an issue if you still have issues.
