### ISSUE TITLE
Unit Tests Fail - Cannot read property 'unshift' - Invalid config file

### ISSUE THREAD

**Issue by christroutner** [misterGF/CoPilot#58]
System: Ubuntu Linux 16.04
Node: 6.11.3
Npm: 5.4.2
For commit: 70ef8c94156073e9f8453da37b31caeb7d6f2fb5

I can successfully run `npm run build`, but when I run `npm run unit` I get the following output:

```
npm run unit

> copilot@0.5.0 unit /home/trout/experiments/original-copilot/coPilot
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

24 09 2017 00:48:45.244:ERROR [config]: Invalid config file!
  TypeError: Cannot read property 'unshift' of undefined
    at Object.<anonymous> (/home/trout/experiments/original-copilot/coPilot/test/unit/karma.conf.js:25:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.parseConfig (/home/trout/experiments/original-copilot/coPilot/node_modules/karma/lib/config.js:363:22)
    at new Server (/home/trout/experiments/original-copilot/coPilot/node_modules/karma/lib/server.js:56:20)
    at Object.exports.run (/home/trout/experiments/original-copilot/coPilot/node_modules/karma/lib/cli.js:280:7)
    at Object.<anonymous> (/home/trout/experiments/original-copilot/coPilot/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! copilot@0.5.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the copilot@0.5.0 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trout/.npm/_logs/2017-09-24T00_48_45_311Z-debug.log

```

**Comment by misterGF** [comment]
Thanks for the details. There was a recently merged PR that fixed this #55. Pull the latest code and let us know if you still have the same issues.
