### ISSUE TITLE
Failed to run.

### ISSUE THREAD

**Issue by hifall** [misterGF/CoPilot#71]
When I do: npm run dev, I get:

> node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 1 errors                                 19:21:42

 error  in ./src/components/Dash.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/gangcailin/Downloads/CoPilot-master/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/Users/gangcailin/Downloads/CoPilot-master/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/Users/gangcailin/Downloads/CoPilot-master/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/gangcailin/Downloads/CoPilot-master/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/gangcailin/Downloads/CoPilot-master/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/gangcailin/Downloads/CoPilot-master/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/gangcailin/Downloads/CoPilot-master/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/gangcailin/Downloads/CoPilot-master/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-61ca42a2","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Dash.vue 4:14-380 13:3-17:5 14:22-388
 @ ./src/components/Dash.vue
 @ ./src/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

Any idea?

Thanks!

**Comment by misterGF** [comment]
Did you get any errors during your npm install?

Might want to try to run it again as admin to make sure you have the required packages. You can inspect your node_modules folder too for the saas-loader folder. Chances are it is missing.
